package com.qualitycyberservices.android.wordlist.db;

import java.util.Date;
import java.util.UUID;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "WORD".
 */
public class Word {

    private Long id;
    /** Not-null value. */
    private UUID UUID;
    private String word;
    /** Not-null value. */
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Word() {
        this( new Date() );
    }

    public Word(Long id) {
        this.id = id;
    }

    public Word(Long id, UUID UUID, String word, java.util.Date date) {
        this.id = id;
        this.UUID = UUID;
        this.word = word;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public UUID getUUID() {
        return UUID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUUID(UUID UUID) {
        this.UUID = UUID;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    public Word( Date date ) {
        this.date = date;
    }
    // KEEP METHODS END

}
